package com.jcortes.deco.content.model

enum class DecorTag(val label: String, val seoUrl: String) {
    LIVING_ROOM_DECOR("Decoración de salones", "decoracion-salones"),
    DINING_ROOM_DECOR("Decoración de comedores", "decoracion-comedores"),
    LIVING_ROOM_FURNITURE("Muebles de salón", "muebles-salon"),
    SOFAS_ARMCHAIRS("Sofás y sillones", "sofas-sillones"),
    DINING_TABLES("Mesas de comedor", "mesas-comedor"),
    INTERIOR_DECOR("Decoración de interiores", "decoracion-interiores"),
    INTERIOR_COLORS("Colores para interiores", "colores-interiores"),
    INTERIOR_LIGHTING("Iluminación en interiores", "iluminacion-interiores"),
    DECOR_STYLES("Estilos de decoración", "estilos-decoracion"),
    MODERN_DECOR("Decoración moderna", "decoracion-moderna"),
    RUSTIC_DECOR("Decoración rústica", "decoracion-rustica"),
    MINIMALIST_DECOR("Decoración minimalista", "decoracion-minimalista"),
    VINTAGE_DECOR("Decoración vintage", "decoracion-vintage"),
    HOME_TEXTILES("Textiles para el hogar", "textiles-hogar"),
    CURTAINS_BLINDS("Cortinas y estores", "cortinas-estores"),
    RUGS_TAPESTRIES("Alfombras y tapices", "alfombras-tapices"),
    DECORATIVE_CUSHIONS("Cojines decorativos", "cojines-decorativos"),
    PLANT_DECOR("Decoración con plantas", "decoracion-plantas"),
    WOOD_DECOR("Decoración con madera", "decoracion-madera"),
    SHELVES_BOOKCASES("Estanterías y librerías", "estanterias-librerias"),
    HOME_ORGANIZATION("Organización en el hogar", "organizacion-hogar"),
    SMALL_SPACES("Espacios pequeños", "espacios-pequenos"),
    KITCHEN_DECOR("Decoración de cocinas", "decoracion-cocinas"),
    OPEN_KITCHENS("Cocinas abiertas", "cocinas-abiertas"),
    KITCHEN_COLORS("Colores para cocinas", "colores-cocinas"),
    KITCHEN_FURNITURE("Muebles de cocina", "muebles-cocina"),
    COUNTERTOPS_SURFACES("Encimeras y superficies", "encimeras-superficies"),
    KITCHEN_LAYOUT("Distribución de cocinas", "distribucion-cocinas"),
    KITCHEN_LIGHTING("Iluminación en cocinas", "iluminacion-cocinas"),
    MODERN_KITCHENS("Cocinas modernas", "cocinas-modernas"),
    RUSTIC_KITCHENS("Cocinas rústicas", "cocinas-rusticas"),
    KIDS_BEDROOMS("Dormitorios infantiles", "dormitorios-infantiles"),
    BEDROOM_DECOR("Decoración de dormitorios", "decoracion-dormitorios"),
    BED_HEADBOARDS("Cabeceros de cama", "cabeceros-cama"),
    BEDDING("Ropa de cama", "ropa-cama"),
    BEDROOM_LIGHTING("Iluminación en dormitorios", "iluminacion-dormitorios"),
    WARDROBES_CLOSET("Armarios y vestidores", "armarios-vestidores"),
    MODERN_BEDROOMS("Dormitorios modernos", "dormitorios-modernos"),
    RUSTIC_BEDROOMS("Dormitorios rústicos", "dormitorios-rusticos"),
    MINIMALIST_BEDROOMS("Dormitorios minimalistas", "dormitorios-minimalistas"),
    BATHROOM_DECOR("Decoración de baños", "decoracion-banos"),
    BATHROOM_COLORS("Colores para baños", "colores-banos"),
    SMALL_BATHROOMS("Baños pequeños", "banos-pequenos"),
    TILES_CERAMICS("Azulejos y cerámica", "azulejos-ceramica"),
    BATHROOM_FURNITURE("Muebles de baño", "muebles-bano"),
    BATHROOM_ACCESSORIES("Accesorios de baño", "accesorios-bano"),
    BATHROOM_LIGHTING("Iluminación en baños", "iluminacion-banos"),
    MODERN_BATHROOMS("Baños modernos", "banos-modernos"),
    RUSTIC_BATHROOMS("Baños rústicos", "banos-rusticos"),
    GARDENS_TERRACES("Jardines y terrazas", "jardines-terrazas"),
    OUTDOOR_DECOR("Decoración de exteriores", "decoracion-exteriores"),
    OUTDOOR_FURNITURE("Muebles de exterior", "muebles-exterior"),
    PLANTS_FLOWERS("Plantas y flores", "plantas-flores"),
    OUTDOOR_LIGHTING("Iluminación exterior", "iluminacion-exterior"),
    SMALL_TERRACES("Terrazas pequeñas", "terrazas-pequenas"),
    PATIOS_GARDENS("Patios y jardines", "patios-jardines"),
    PERGOLAS_AWNINGS("Pérgolas y toldos", "pergolas-toldos"),
    SEASONAL_DECOR("Decoración estacional", "decoracion-estacional"),
    CHRISTMAS_DECOR("Decoración de Navidad", "decoracion-navidad"),
    SPRING_DECOR("Decoración de primavera", "decoracion-primavera"),
    SUMMER_DECOR("Decoración de verano", "decoracion-verano"),
    FALL_DECOR("Decoración de otoño", "decoracion-otono"),
    DECOR_TRENDS("Tendencias de decoración", "tendencias-decoracion"),
    DIY_DECOR("DIY decoración", "diy-decoracion"),
    LOW_COST_DECOR("Decoración low cost", "decoracion-low-cost"),
    RECYCLED_DECOR("Reciclaje y decoración", "reciclaje-decoracion"),
    DECOR_ART("Arte y cuadros decorativos", "arte-cuadros-decorativos"),
    DECOR_MIRRORS("Espejos decorativos", "espejos-decorativos"),
    WALLPAPERS("Papeles pintados", "papeles-pintados"),
    WALLS_COVERINGS("Paredes y revestimientos", "paredes-revestimientos"),
    HOME_RENOVATIONS("Reformas del hogar", "reformas-hogar"),
    SPACE_LAYOUT("Distribución de espacios", "distribucion-espacios"),
    INTERIOR_DESIGN("Diseño de interiores", "diseno-interiores");

    companion object {
        fun fromLabel(label: String): DecorTag? {
            return entries.find { it.label.lowercase() == label.lowercase() }
        }
    }
}